### ISSUE TITLE
Repleace enormous jpg files, with webp 

### ISSUE THREAD

**Issue by Horki** [udacity/CppND-Program-a-Concurrent-Traffic-Simulation#9]
@swwelch please replace jpeg data with modern webp format, like [here](https://github.com/Horki/CppND-Program-a-Concurrent-Traffic-Simulation/tree/master/data)

**Comment by SudKul** [comment]
Hi @Horki 
Thanks for the suggestion. We have accommodated your proposal in this [commit](https://github.com/udacity/CppND-Program-a-Concurrent-Traffic-Simulation/commit/e892971f71c990070ddd3a5e07f689f94bd86854).
